/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test123;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import static test123.login.dockUser;
import static test123.login.frame;
import static test123.login.user;

/**
 *
 * @author I3
 */
public class lobby extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public lobby() {
        initComponents();        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_User = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 552));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(255, 255, 51));
        jButton7.setText("INVITE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 90, 30));

        jLabel1.setBackground(java.awt.Color.gray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 100));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Username  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 30));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shutdown_18px.png"))); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 110, 30));

        jTextField2.setBackground(new java.awt.Color(204, 255, 204));
        jTextField2.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 340, -1));

        jButton2.setBackground(new java.awt.Color(23, 243, 63));
        jButton2.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/แก้ไข_15px.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, 30));

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TOTAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 90, -1));

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Score :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, 30));

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WIN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, -1));

        jLabel6.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DRAW");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 90, -1));

        jLabel7.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOSE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 90, -1));

        jTextField3.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 204, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("-");
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 90, 30));

        jTextField6.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 204, 51));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("-");
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 90, 30));

        jTextField7.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 204, 51));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("-");
        jTextField7.setEnabled(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 90, 30));

        jTextField8.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 204, 51));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("-");
        jTextField8.setEnabled(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 90, 30));

        jLabel8.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("ONLINE PLAYERS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 170, 30));

        jButton3.setBackground(new java.awt.Color(74, 226, 162));
        jButton3.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Leaderboard_17px.png"))); // NOI18N
        jButton3.setText("RANKING");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 30));

        jButton4.setBackground(new java.awt.Color(138, 226, 189));
        jButton4.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules_17px.png"))); // NOI18N
        jButton4.setText("RULES");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 110, 30));

        jButton5.setBackground(new java.awt.Color(71, 239, 163));
        jButton5.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game Controller_17px.png"))); // NOI18N
        jButton5.setText("MATCHING");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 120, 30));

        list_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(list_User);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 680, 320));

        jButton8.setBackground(new java.awt.Color(102, 255, 102));
        jButton8.setText("refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       logout();
        login form = new login();
        frame.setContentPane(form);
        frame.pack();
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);       
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
public void logout(){
             BasicDBObject documents = new BasicDBObject();
            documents.put("username",(String) dockUser.get("username"));
            BasicDBObject searchQuery = new BasicDBObject();
            BasicDBObject status = new BasicDBObject();
            status.put("status","offline");
            searchQuery.put("$set",status);
            user.update(documents, searchQuery);  
}
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(!list_User.getSelectionModel().isSelectionEmpty()){
        String name =(String) list_User.getModel().getValueAt( list_User.getSelectedRow(),0);
        letInvite(name);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        letMatching();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         setLobbyTable();
    }//GEN-LAST:event_jButton8ActionPerformed
public void setMyinfo(DBObject dockUser){
    jTextField2.setText((String) dockUser.get("username")+"  A.K.A  "+(String) dockUser.get("name"));
    int win = (Integer) dockUser.get("score_win");
    int lose = (Integer) dockUser.get("score_lose");
    int draw = (Integer) dockUser.get("score_draw");
    int total=win+lose+draw;
    jTextField6.setText(Integer.toString(win));
    jTextField7.setText(Integer.toString(lose));
    jTextField8.setText(Integer.toString(draw));
    jTextField6.setText(Integer.toString(total));
    int icon = (Integer) dockUser.get("icon");
    if(icon==0){
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_038.gif")));
    }else if(icon==1){
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_042.gif")));
    }else if(icon==2){
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_040.gif")));
    }
    setLobbyTable();
    
    
}

public void gotoRanking(){
//        rankForm rank = new rankForm();
//        frame.setContentPane(rank.mainPanel);
    }

    public void gotoEdit(){
//        editForm edit = new editForm();
//        frame.setContentPane(edit.mainPanel);
    }

    public void gotoLogin(){
//        loginForm login = new loginForm();
//        frame.setContentPane(login.mainPanel);

    }

    public void gotoRules(){
//        rulesForm rules = new rulesForm();
//        frame.setContentPane(rules.mainPanel);
    }

    public void letMatching(){

        showMessageMatching();
    }

    public void letInvite(String name){

        showMessageWaitAccept(name);
    }

    public void gotoGame(){
//        gameForm game = new gameForm();
//        frame.setContentPane(game.mainPanel);

    }
//public void setLobby(){
//        DBCursor cursor = user.find();         
//                     
//             while (cursor.hasNext()) {
//                DBObject dockran= cursor.next();
//                if(!dockran.get("status").equals("offline")){
//               setTextField(jTextField22,jTextField39,jTextField40,jTextField43,dockran);
//               jTextField40.setText((String) dockran.get("score_lose"));
//               jTextField43.setText((String) dockran.get("score_draw"));
//                }
//             }
////        lobbyForm lobby = new lobbyForm();
////        frame.setContentPane(lobby.mainPanel);
//    }
    public void setLobbyTable(){
        
          
        DBCursor cursor = user.find();         
            String[] columnNames = {"name", "win", "draw","lose"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            while(cursor.hasNext()) {
                DBObject obj = cursor.next();
                 if(!obj.get("status").equals("offline")&&!obj.get("username").equals((String)dockUser.get("username"))){
                String name = (String)obj.get("name");
                String win = Integer.toString((Integer)obj.get("score_win"));
                String draw = Integer.toString((Integer)obj.get("score_draw"));
                String lose = Integer.toString((Integer)obj.get("score_lose"));
                 model.addRow(new Object[] { name, win,draw, lose });
                }
                
               
        }
        list_User.setModel(model);

        cursor.close(); 
         
    }
     public void setTextField(JTextField t1,JTextField t2,JTextField t3,JTextField t4,DBObject dockran){
                t1.setText((String) dockran.get("name")+" A.K.A. "+(String) dockran.get("username"));
              t2.setText((String) dockran.get("score_win"));
               t3.setText((String) dockran.get("score_lose"));
               t4.setText((String) dockran.get("score_draw"));
     }

    public void showMessageMatching(){
        JOptionPane.showMessageDialog(null, "Matching...");
        if(JOptionPane.CANCEL_OPTION==2){

        }
    }

    public void showMessageWaitAccept(String name){
        JOptionPane.showMessageDialog(null, "Waiting..."+name);
        if(JOptionPane.CANCEL_OPTION==2){

        }
    }

    public void showMessageBusy(){
        JOptionPane.showMessageDialog(null, "Your friend is busy");
    }

    public void showMessageInvite(){
        JOptionPane.showMessageDialog(null, "Someone invite you");
        if(JOptionPane.YES_OPTION==0){
            gotoGame();
        }
    }
    public void updateIsMatching(){

    }

    public void updeteIsMatched(){

    }

    public void updateIsDefault(){

    }

    public void updateIsInviting(){

    }

    public void matchStatus(){

    }

    public void checkStatus(){

    }

    public void checkAccept(){

    }
    Timer tm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable list_User;
    // End of variables declaration//GEN-END:variables
}
