/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test123;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import java.awt.Dimension;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author I3
 */
public class login extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_usernabe = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        lab_username = new javax.swing.JLabel();
        lab_password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();

        login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N

        txt_usernabe.setBackground(new java.awt.Color(204, 255, 204));

        btn_login.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 51, 51));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MelodicCarelessBluemorphobutterfly-size_restricted.gif"))); // NOI18N
        btn_login.setText("Login");
        btn_login.setActionCommand("");
        btn_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_register.setBackground(new java.awt.Color(0, 51, 51));
        btn_register.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(0, 51, 51));
        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b2.png"))); // NOI18N
        btn_register.setText("Register");
        btn_register.setAutoscrolls(true);
        btn_register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        lab_username.setBackground(new java.awt.Color(0, 102, 102));
        lab_username.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        lab_username.setForeground(new java.awt.Color(0, 153, 102));
        lab_username.setText("Username  :");

        lab_password.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        lab_password.setForeground(new java.awt.Color(0, 153, 102));
        lab_password.setText("Password  :");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VNsi.gif"))); // NOI18N

        txt_password.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(lab_password)
                        .addGap(26, 26, 26)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(lab_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_usernabe, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usernabe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_username))
                .addGap(45, 45, 45)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_password)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
       
        if(txt_usernabe.getText().equals("")||txt_password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "กรุณากรอกข้อมูลให้ครบถ้วน");
        }
        else{
            BasicDBObject searchQuery  = new BasicDBObject();
        searchQuery.put("username",txt_usernabe.getText());
        dockUser = user.findOne(searchQuery);
            if(Vertify_Username(txt_usernabe.getText(),txt_password.getText(),dockUser)){
                //login fin
                JOptionPane.showMessageDialog(null, "ล็อคอินสำเร็จ");
                lobby form = new lobby();
                frame.setContentPane(form);
                frame.pack();
                
                frame.setVisible(true);
                form.setMyinfo(dockUser);
                
                BasicDBObject documents = new BasicDBObject();
            documents.put("username",(String) dockUser.get("username"));
            BasicDBObject search_user = new BasicDBObject();
            BasicDBObject status = new BasicDBObject();
            status.put("status","online");
            search_user.put("$set",status);
            user.update(documents, search_user); 
                
            }else{
                JOptionPane.showMessageDialog(null, "username หรือ password ผิดพลาด");
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed
    public static boolean Vertify_Username(String username,String password,DBObject dockUser){
       
        if(is_Username_Exit(username,dockUser) && is_Password_Correct(password,dockUser)){
            return true;
        }
        return false;
    }
    
    public static boolean is_Username_Exit(String username,DBObject dockUser){
        
        if(dockUser != null){
            return true;
        }
        return false;
    }
    public static boolean is_Password_Correct(String password,DBObject dockUser){
        String passInDB = (String) dockUser.get("password");
        if(passInDB.equals(password)){
            return true;
        }
        return false;
    }
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        Regis();
    }//GEN-LAST:event_btn_registerActionPerformed
    public void Regis(){  
        register form = new register();
        Display_Regis(form);
        
    }
    public void Display_Regis(JPanel regis){
        frame.setContentPane(regis);
        frame.pack();    
        frame.setVisible(true);
        
    }
    static MongoClientURI uri ;
    static MongoClient mongo ;
    static DB db;
    static DBCollection user;
    static DBObject dockUser;
    static JFrame frame;
   
    
    
    public static void main(String[] args) {
         frame = new JFrame();
        login form = new login();
        frame.setContentPane(form);
        frame.pack();
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);        
        frame.setVisible(true);
        connect();

    }
    public static void connect(){
        try {
            uri = new MongoClientURI("mongodb://dbboat:boat1234@ds245512.mlab.com:45512/dbxo");
            mongo = new MongoClient(uri);
            db = mongo.getDB(uri.getDatabase());
            user = db.getCollection("user");
            System.out.print("success");
        }catch (IOException ex) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lab_password;
    private javax.swing.JLabel lab_username;
    private javax.swing.JPanel login;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usernabe;
    // End of variables declaration//GEN-END:variables
}
