/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test123;

import com.mongodb.BasicDBObject;
import com.mongodb.DBObject;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import static test123.login.dockUser;
import static test123.login.frame;
import static test123.login.user;

/**
 *
 * @author I3
 */
public class register extends javax.swing.JPanel {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_yourname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lab_selectPic1 = new javax.swing.JLabel();
        lab_selectPic2 = new javax.swing.JLabel();
        lab_selectPic3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lab_yourname = new javax.swing.JLabel();
        lab_username = new javax.swing.JLabel();
        lab_password = new javax.swing.JLabel();
        lab_confirmPassword = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_confirmPassword = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N

        txt_yourname.setBackground(new java.awt.Color(204, 255, 204));
        txt_yourname.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txt_yourname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yournameActionPerformed(evt);
            }
        });

        txt_username.setBackground(new java.awt.Color(204, 255, 204));
        txt_username.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lab_selectPic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_038.gif"))); // NOI18N
        lab_selectPic1.setText("jLabel2");
        lab_selectPic1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_selectPic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_selectPic1MouseClicked(evt);
            }
        });

        lab_selectPic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_042.gif"))); // NOI18N
        lab_selectPic2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_selectPic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_selectPic2MouseClicked(evt);
            }
        });

        lab_selectPic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_040.gif"))); // NOI18N
        lab_selectPic3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lab_selectPic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_selectPic3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lab_selectPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab_selectPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lab_selectPic3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_selectPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_selectPic2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_selectPic3)
                    .addComponent(jLabel11))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        lab_yourname.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        lab_yourname.setForeground(new java.awt.Color(0, 153, 102));
        lab_yourname.setText("Yourname");

        lab_username.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        lab_username.setForeground(new java.awt.Color(0, 153, 102));
        lab_username.setText("Username");

        lab_password.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        lab_password.setForeground(new java.awt.Color(0, 153, 102));
        lab_password.setText("Password");

        lab_confirmPassword.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        lab_confirmPassword.setForeground(new java.awt.Color(0, 153, 102));
        lab_confirmPassword.setText("Confirm Password");

        btn_submit.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(0, 51, 51));
        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MelodicCarelessBluemorphobutterfly-size_restricted.gif"))); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(255, 102, 204));
        btn_cancel.setFont(new java.awt.Font("Riviera", 1, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(0, 51, 51));
        btn_cancel.setText("Cancel");
        btn_cancel.setAutoscrolls(true);
        btn_cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N

        txt_password.setBackground(new java.awt.Color(204, 255, 204));

        txt_confirmPassword.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_password)
                                            .addComponent(lab_yourname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lab_password, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_yourname, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                        .addGap(117, 117, 117)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(lab_username)
                            .addComponent(lab_confirmPassword)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_confirmPassword))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(10, 10, 10)
                                .addComponent(lab_yourname))
                            .addComponent(lab_username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_yourname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_confirmPassword)
                            .addComponent(lab_password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_yournameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yournameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yournameActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        Submit();
    }//GEN-LAST:event_btn_submitActionPerformed
    public void Submit() {
        BasicDBObject searchQuery  = new BasicDBObject();
        searchQuery.put("username",txt_username.getText());
        dockUser = user.findOne(searchQuery);
        if(checkInput(dockUser)){
             save_Regis();
            show_message();

        }
        
    }
    public boolean checkInput(DBObject dockuser) {
        if(Check_user_wrong(dockuser)&&Check_complete_inform()
                &&Check_password_wrong()&&Check_meet_condition()){
            return true;
        }
            
        return false;
    }
     public boolean Check_user_wrong(DBObject dockuser) {
        if(dockUser!=null){
         JOptionPane.showMessageDialog(null, "username ซ้ำ");
         return false;
        }
         return true;
    }
      public boolean Check_password_wrong() {
        if(txt_password.getText().length()<8){
            JOptionPane.showMessageDialog(null, "password 8 ตัวอักษรขึ้นไป");
            return false;
        }
         return true;
    }
       public boolean Check_meet_condition() {
        if(!txt_password.getText().equals(txt_confirmPassword.getText())){
            JOptionPane.showMessageDialog(null, "password ไม่ตรงกัน");
        return false;
        }
         return true;
    }
       public boolean Check_complete_inform() {
        if(txt_yourname.getText().isEmpty()||txt_password.getText().isEmpty()||txt_username.getText().isEmpty()||txt_confirmPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ใส่ข้อมูลให้ครบ");
            return false;
        }
         return true;
    }
    public void save_Regis() {
        BasicDBObject add = new BasicDBObject();
            add.put("name", txt_yourname.getText());
            add.put("username", txt_username.getText());
            add.put("password", new String(txt_password.getText()));
            add.put("score_win", 0);
            add.put("score_lose", 0);
            add.put("score_draw", 0);
            add.put("status", "offline");
            add.put("icon", icon);
            user.insert(add);
            txt_yourname.setText(null);
            txt_username.setText(null);
            txt_password.setText(null);
            txt_confirmPassword.setText(null);
          
    }
     public void show_message() {
        JOptionPane.showMessageDialog(null, "success");
    }
    
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       login form = new login();
        frame.setContentPane(form);
        frame.pack();   
        frame.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void lab_selectPic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_selectPic1MouseClicked
        icon=0;
    }//GEN-LAST:event_lab_selectPic1MouseClicked

    private void lab_selectPic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_selectPic2MouseClicked
        icon =1;
    }//GEN-LAST:event_lab_selectPic2MouseClicked

    private void lab_selectPic3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_selectPic3MouseClicked
        icon=2;
    }//GEN-LAST:event_lab_selectPic3MouseClicked
static int icon =0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab_confirmPassword;
    private javax.swing.JLabel lab_password;
    private javax.swing.JLabel lab_selectPic1;
    private javax.swing.JLabel lab_selectPic2;
    private javax.swing.JLabel lab_selectPic3;
    private javax.swing.JLabel lab_username;
    private javax.swing.JLabel lab_yourname;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_yourname;
    // End of variables declaration//GEN-END:variables
}
