/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameXO;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author I3
 */
public class Lobby extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Lobby() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_invite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        txt_showUsername = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        win = new javax.swing.JLabel();
        draw = new javax.swing.JLabel();
        lose = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_win = new javax.swing.JTextField();
        txt_draw = new javax.swing.JTextField();
        txt_lose = new javax.swing.JTextField();
        online_player = new javax.swing.JLabel();
        btn_ranking = new javax.swing.JButton();
        btn_rules = new javax.swing.JButton();
        btn_matching = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_User = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 552));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_invite.setBackground(new java.awt.Color(255, 255, 51));
        btn_invite.setText("INVITE");
        btn_invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inviteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_invite, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 90, 30));

        jLabel1.setBackground(java.awt.Color.gray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 100));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setFont(new java.awt.Font("TH SarabunPSK", 1, 26)); // NOI18N
        username.setForeground(new java.awt.Color(0, 153, 51));
        username.setText("Username  :");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, 30));

        btn_logout.setBackground(new java.awt.Color(255, 204, 102));
        btn_logout.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shutdown_18px.png"))); // NOI18N
        btn_logout.setText("LOG OUT");
        btn_logout.setBorder(null);
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 110, 30));

        txt_showUsername.setBackground(new java.awt.Color(204, 255, 204));
        txt_showUsername.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_showUsername.setEnabled(false);
        txt_showUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_showUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_showUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 340, -1));

        btn_edit.setBackground(new java.awt.Color(23, 243, 63));
        btn_edit.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/แก้ไข_15px.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, 30));

        total.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        total.setForeground(new java.awt.Color(0, 153, 51));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("TOTAL");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 90, -1));

        score.setFont(new java.awt.Font("TH Sarabun New", 1, 22)); // NOI18N
        score.setForeground(new java.awt.Color(0, 153, 51));
        score.setText("Score :");
        jPanel1.add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, 30));

        win.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        win.setForeground(new java.awt.Color(0, 153, 51));
        win.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        win.setText("WIN");
        jPanel1.add(win, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, -1));

        draw.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        draw.setForeground(new java.awt.Color(0, 153, 51));
        draw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        draw.setText("DRAW");
        jPanel1.add(draw, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 90, -1));

        lose.setFont(new java.awt.Font("TH Sarabun New", 1, 19)); // NOI18N
        lose.setForeground(new java.awt.Color(0, 153, 51));
        lose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lose.setText("LOSE");
        jPanel1.add(lose, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 90, -1));

        txt_total.setBackground(new java.awt.Color(204, 255, 204));
        txt_total.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(0, 204, 51));
        txt_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_total.setText("-");
        txt_total.setEnabled(false);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 90, 30));

        txt_win.setBackground(new java.awt.Color(204, 255, 204));
        txt_win.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_win.setForeground(new java.awt.Color(0, 204, 51));
        txt_win.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_win.setText("-");
        txt_win.setEnabled(false);
        txt_win.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_winActionPerformed(evt);
            }
        });
        jPanel1.add(txt_win, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 90, 30));

        txt_draw.setBackground(new java.awt.Color(204, 255, 204));
        txt_draw.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_draw.setForeground(new java.awt.Color(0, 204, 51));
        txt_draw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_draw.setText("-");
        txt_draw.setEnabled(false);
        txt_draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_drawActionPerformed(evt);
            }
        });
        jPanel1.add(txt_draw, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 90, 30));

        txt_lose.setBackground(new java.awt.Color(204, 255, 204));
        txt_lose.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        txt_lose.setForeground(new java.awt.Color(0, 204, 51));
        txt_lose.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_lose.setText("-");
        txt_lose.setEnabled(false);
        txt_lose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loseActionPerformed(evt);
            }
        });
        jPanel1.add(txt_lose, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 90, 30));

        online_player.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        online_player.setForeground(new java.awt.Color(0, 153, 51));
        online_player.setText("ONLINE PLAYERS");
        jPanel1.add(online_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 170, 30));

        btn_ranking.setBackground(new java.awt.Color(74, 226, 162));
        btn_ranking.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        btn_ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Leaderboard_17px.png"))); // NOI18N
        btn_ranking.setText("RANKING");
        jPanel1.add(btn_ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 30));

        btn_rules.setBackground(new java.awt.Color(138, 226, 189));
        btn_rules.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        btn_rules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rules_17px.png"))); // NOI18N
        btn_rules.setText("RULES");
        jPanel1.add(btn_rules, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 110, 30));

        btn_matching.setBackground(new java.awt.Color(71, 239, 163));
        btn_matching.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        btn_matching.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Game Controller_17px.png"))); // NOI18N
        btn_matching.setText("MATCHING");
        btn_matching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matchingActionPerformed(evt);
            }
        });
        jPanel1.add(btn_matching, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 120, 30));

        list_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(list_User);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 680, 320));

        btn_refresh.setBackground(new java.awt.Color(102, 255, 102));
        btn_refresh.setText("refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        String temp = txt_showUsername.getText();
        LobbyService.logout(temp.substring(0, temp.indexOf(' ')));
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void txt_showUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_showUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_showUsernameActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_winActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_winActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_winActionPerformed

    private void txt_drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_drawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_drawActionPerformed

    private void txt_loseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loseActionPerformed

    private void btn_inviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inviteActionPerformed
        if(!list_User.getSelectionModel().isSelectionEmpty()){
        String name =(String) list_User.getModel().getValueAt( list_User.getSelectedRow(),0);
        LobbyService.letInvite(name);
        }
    }//GEN-LAST:event_btn_inviteActionPerformed

    private void btn_matchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matchingActionPerformed
        LobbyService.letMatching();
    }//GEN-LAST:event_btn_matchingActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
           setLobbyTable();
    }//GEN-LAST:event_btn_refreshActionPerformed



 void setLobby(Users users){
    
    txt_showUsername.setText((String) users.username+"  A.K.A  "+(String) users.name);
    int win = (Integer) users.score_win;
    int lose = (Integer) users.score_lose;
    int draw = (Integer) users.score_draw;
    int total=win+lose+draw;
    txt_win.setText(Integer.toString(win));
    txt_draw.setText(Integer.toString(lose));
    txt_lose.setText(Integer.toString(draw));
    txt_win.setText(Integer.toString(total));
    int icon = (Integer) users.icon;
    if(icon==0){
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_038.gif")));
    }else if(icon==1){
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_042.gif")));
    }else if(icon==2){
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_040.gif")));
    }
    setLobbyTable();
}
 void setLobbyTable(){
     ArrayList<Users> userList=Database.getAll();
    String[] columnNames = {"name", "win", "draw","lose"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);
            String temp = txt_showUsername.getText();
            for(Users list:userList)
                 if(!list.status.equals("offline")&&!list.username.equals(temp.substring(0, temp.indexOf(' ')))){
                String name = list.name;
                String win = Integer.toString(list.score_win);
                String draw = Integer.toString(list.score_draw);
                String lose = Integer.toString(list.score_lose);
                 model.addRow(new Object[] { name, win,draw, lose });
                }
                
               list_User.setModel(model);
        }
        


     

    

    

    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_invite;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_matching;
    private javax.swing.JButton btn_ranking;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_rules;
    private javax.swing.JLabel draw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable list_User;
    private javax.swing.JLabel lose;
    private javax.swing.JLabel online_player;
    private javax.swing.JLabel score;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txt_draw;
    private javax.swing.JTextField txt_lose;
    private javax.swing.JTextField txt_showUsername;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_win;
    private javax.swing.JLabel username;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
